/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type TimelineRowImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "timelineRow.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type ListedDocumentFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "file.media" in schema
  _type: 'file';
};

export type LinkCardImage = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "linkCard.image.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type Photo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "photo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: 'image';
};

export type Redirect = {
  _id: string;
  _type: 'redirect';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
  note?: string;
};

export type SectionPreset = {
  _id: string;
  _type: 'sectionPreset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sectionType?: string;
  section?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & SundayTimesSection)
    | ({
        _key: string;
      } & TimelineSection)
    | ({
        _key: string;
      } & StaffGridSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ScriptureBandSection)
    | ({
        _key: string;
      } & HeritageBandSection)
    | ({
        _key: string;
      } & GiveBandSection)
    | ({
        _key: string;
      } & HoursSection)
    | ({
        _key: string;
      } & DocumentListSection)
    | ({
        _key: string;
      } & LinkCardsSection)
    | ({
        _key: string;
      } & MinistrySection)
    | ({
        _key: string;
      } & WatchwordSection)
    | ({
        _key: string;
      } & GoalsSection)
    | ({
        _key: string;
      } & PledgeSection)
    | ({
        _key: string;
      } & LetterSection)
    | ({
        _key: string;
      } & ChurchTracFormSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & DynamicListSection)
  >;
  note?: string;
};

export type StaffMember = {
  _id: string;
  _type: 'staffMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  email?: string;
  phone?: string;
  group?: 'pastors' | 'coordination' | 'support';
  showOnSite?: boolean;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type JournalCategory = {
  _id: string;
  _type: 'journalCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Announcement = {
  _id: string;
  _type: 'announcement';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  message?: string;
  style?: 'info' | 'highlight' | 'urgent';
  link?: {
    label?: string;
    url?: string;
  };
  startDate?: string;
  endDate?: string;
  enabled?: boolean;
};

export type StudioNotes = {
  _id: string;
  _type: 'studioNotes';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessSummary?: string;
  idealClient?: string;
  voiceSummary?: string;
  wordsToAvoid?: Array<string>;
};

export type StudioGuide = {
  _id: string;
  _type: 'studioGuide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  guideTitle?: string;
  guideIntro?: string;
  studioMap?: Array<{
    area?: string;
    description?: string;
    _type: 'mapRow';
    _key: string;
  }>;
  howTos?: Array<{
    title?: string;
    steps?: Array<string>;
    _type: 'howTo';
    _key: string;
  }>;
  tips?: Array<{
    heading?: string;
    tone?: 'default' | 'primary' | 'caution' | 'positive';
    body?: string;
    _type: 'tip';
    _key: string;
  }>;
};

export type NotFoundPage = {
  _id: string;
  _type: 'notFoundPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  eyebrow?: string;
  headline?: string;
  body?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  primaryCtaLabel?: string;
  primaryCtaHref?: string;
  secondaryCtaLabel?: string;
  secondaryCtaHref?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaHref?: string;
  fourthCtaLabel?: string;
  fourthCtaHref?: string;
};

export type BusinessInfo = {
  _id: string;
  _type: 'businessInfo';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  businessModel?: 'in-person' | 'remote' | 'hybrid';
  city?: string;
  state?: string;
  serviceRegion?: string;
  geoLat?: number;
  geoLng?: number;
  additionalLocations?: Array<{
    city?: string;
    state?: string;
    geoLat?: number;
    geoLng?: number;
    _type: 'additionalLocation';
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  email?: string;
  phone?: string;
  serviceTime?: string;
  serviceLength?: string;
  address?: string;
  officeHours?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  pastoralHours?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  churchCenterUrl?: string;
  churchTracUrl?: string;
  youtubeUrl?: string;
  livestreamUrl?: string;
  mapImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  directionsUrl?: string;
  givingUrl?: string;
  visitorFormUrl?: string;
  lifeEventFormUrl?: string;
  sermonsUrl?: string;
  wednesdayUrl?: string;
  calendarUrl?: string;
  prayerUrl?: string;
  appUrl?: string;
  weddingEnquiryUrl?: string;
  weddingBookingUrl?: string;
  navItems?: Array<
    | ({
        _key: string;
      } & NavLink)
    | {
        label?: string;
        links?: Array<{
          label?: string;
          href?: string;
          _type: 'navSubLink';
          _key: string;
        }>;
        _type: 'navGroup';
        _key: string;
      }
  >;
  footerColumns?: Array<{
    title?: string;
    links?: Array<
      | ({
          _key: string;
        } & NavLink)
      | {
          label?: string;
          href?: string;
          _type: 'footerLink';
          _key: string;
        }
    >;
    _type: 'footerColumn';
    _key: string;
  }>;
  headerCta?: {
    show?: boolean;
    label?: string;
    link?: NavLink;
  };
  showEmail?: boolean;
  showSocials?: boolean;
  showFooterSocials?: boolean;
  legalNav?: Array<
    {
      _key: string;
    } & NavLink
  >;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  socialInstagram?: string;
  socialFacebook?: string;
  socialLinks?: Array<{
    platform?:
      | 'Instagram'
      | 'Facebook'
      | 'LinkedIn'
      | 'Pinterest'
      | 'YouTube'
      | 'TikTok'
      | 'X'
      | 'Houzz'
      | 'Other';
    url?: string;
    label?: string;
    _type: 'socialLink';
    _key: string;
  }>;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  footerCredit?: string;
  footerCreditUrl?: string;
  newsletter?: {
    enabled?: boolean;
    providerLabel?: string;
    formActionUrl?: string;
    audienceId?: string;
    heading?: string;
    blurb?: string;
    buttonLabel?: string;
    successMessage?: string;
    consentNote?: string;
  };
  sectionVisibility?: {
    showJournal?: boolean;
  };
};

export type HomePageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'homePage';
};

export type JournalPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalPage';
};

export type PrivacyPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'privacyPage';
};

export type PageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'page';
};

export type NavLink = {
  _type: 'navLink';
  label?: string;
  linkType?: 'internal' | 'external';
  internalPage?: HomePageReference | JournalPageReference | PrivacyPageReference | PageReference;
  externalUrl?: string;
  href?: string;
};

export type DynamicListSection = {
  _type: 'dynamicListSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  columns?: 2 | 3;
  source?: 'journal';
  limit?: number;
  cta?: CtaBlock;
  anchor?: Slug;
};

export type TeamSection = {
  _type: 'teamSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  members?: Array<{
    name?: string;
    role?: string;
    photo?: Photo;
    bio?: string;
    socialLinks?: Array<{
      label?: string;
      url?: string;
      _type: 'socialLink';
      _key: string;
    }>;
    _type: 'teamMember';
    _key: string;
  }>;
};

export type ChurchTracFormReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'churchTracForm';
};

export type ChurchTracFormSection = {
  _type: 'churchTracFormSection';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  form?: ChurchTracFormReference;
  anchor?: Slug;
};

export type ChurchTracForm = {
  _id: string;
  _type: 'churchTracForm';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  embed?: string;
  size?: 'short' | 'medium' | 'long';
};

export type LetterSection = {
  _type: 'letterSection';
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  signature?: string;
  signatureNote?: string;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  anchor?: Slug;
};

export type PledgeSection = {
  _type: 'pledgeSection';
  heading?: string;
  intro?: string;
  instruction?: string;
  opening?: string;
  lines?: Array<{
    text?: string;
    reference?: string;
    _type: 'pledgeLine';
    _key: string;
  }>;
  after?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  anchor?: Slug;
};

export type GoalsSection = {
  _type: 'goalsSection';
  heading?: string;
  intro?: string;
  goals?: Array<{
    name?: string;
    subtitle?: string;
    aside?: string;
    glyph?: 'window' | 'door' | 'rose' | 'basin';
    summary?: string;
    quote?: string;
    points?: Array<{
      title?: string;
      short?: string;
      body?: string;
      _type: 'goalPoint';
      _key: string;
    }>;
    photos?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }>;
    _type: 'goal';
    _key: string;
  }>;
  anchor?: Slug;
};

export type WatchwordSection = {
  _type: 'watchwordSection';
  heading?: string;
  intro?: string;
  more?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  verse?: string;
  reference?: string;
  praise?: string;
  proclaim?: string;
  anchor?: Slug;
};

export type MinistryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'ministry';
};

export type MinistrySection = {
  _type: 'ministrySection';
  ministry?: MinistryReference;
  imageSide?: 'left' | 'right';
  anchor?: Slug;
};

export type StaffMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'staffMember';
};

export type Ministry = {
  _id: string;
  _type: 'ministry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  headline?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  contacts?: Array<
    {
      _key: string;
    } & StaffMemberReference
  >;
  goal?: 'worship' | 'the-way' | 'witness' | 'work';
  summary?: string;
  order?: number;
};

export type LinkCardsSection = {
  _type: 'linkCardsSection';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  cards?: Array<{
    title?: string;
    body?: string;
    cta?: CtaBlock;
    image?: LinkCardImage;
    glyph?: 'window' | 'door' | 'rose' | 'basin';
    _type: 'linkCard';
    _key: string;
  }>;
  anchor?: Slug;
};

export type DocumentListSection = {
  _type: 'documentListSection';
  eyebrow?: string;
  heading?: string;
  docs?: Array<{
    title?: string;
    year?: number;
    file?: ListedDocumentFile;
    url?: string;
    note?: string;
    _type: 'listedDocument';
    _key: string;
  }>;
  anchor?: Slug;
};

export type HoursSection = {
  _type: 'hoursSection';
  eyebrow?: string;
  heading?: string;
  anchor?: Slug;
};

export type GiveBandSection = {
  _type: 'giveBandSection';
  heading?: string;
  body?: string;
  buttonLabel?: string;
  buttonUrl?: string;
  anchor?: Slug;
};

export type HeritageBandSection = {
  _type: 'heritageBandSection';
  eyebrow?: string;
  heading?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  archive?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  dates?: Array<{
    now?: boolean;
    year?: string;
    text?: string;
    _type: 'heritageDate';
    _key: string;
  }>;
  cta?: CtaBlock;
  anchor?: Slug;
};

export type ScriptureBandSection = {
  _type: 'scriptureBandSection';
  heading?: string;
  verse?: string;
  reference?: string;
  accentWord?: string;
  intro?: string;
  anchor?: Slug;
};

export type FaqSection = {
  _type: 'faqSection';
  eyebrow?: string;
  heading?: string;
  items?: Array<{
    question?: string;
    answer?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    _type: 'faqItem';
    _key: string;
  }>;
  anchor?: Slug;
};

export type StaffGridSection = {
  _type: 'staffGridSection';
  eyebrow?: string;
  heading?: string;
  group?: 'all' | 'pastors' | 'coordination' | 'support';
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  showBios?: boolean;
  anchor?: Slug;
};

export type TimelineSection = {
  _type: 'timelineSection';
  eyebrow?: string;
  heading?: string;
  rows?: Array<{
    marker?: string;
    title?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }>;
    note?: string;
    image?: TimelineRowImage;
    anchor?: Slug;
    _type: 'timelineRow';
    _key: string;
  }>;
  anchor?: Slug;
};

export type SundayTimesSection = {
  _type: 'sundayTimesSection';
  eyebrow?: string;
  heading?: string;
  intro?: string;
  items?: Array<{
    label?: string;
    big?: string;
    body?: string;
    _type: 'timeItem';
    _key: string;
  }>;
  notes?: Array<string>;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  cta?: CtaBlock;
  doors?: Array<{
    name?: string;
    body?: string;
    _type: 'door';
    _key: string;
  }>;
  showMap?: boolean;
  anchor?: Slug;
};

export type EmbedSection = {
  _type: 'embedSection';
  eyebrow?: string;
  headline?: string;
  subhead?: string;
  embedUrl?: string;
  embedCode?: string;
  heightHint?: 'short' | 'medium' | 'tall';
};

export type LogoStripSection = {
  _type: 'logoStripSection';
  eyebrow?: string;
  headline?: string;
  logos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  layout?: 'row' | 'grid';
  anchor?: Slug;
};

export type SpacerSection = {
  _type: 'spacerSection';
  variant?: 'ornament' | 'line' | 'space';
};

export type VideoSection = {
  _type: 'videoSection';
  url?: string;
  heading?: string;
  caption?: string;
};

export type CtaBandSection = {
  _type: 'ctaBandSection';
  eyebrow?: string;
  headline?: string;
  scriptAccent?: string;
  headingAccent?: string;
  subhead?: string;
  subheadRich?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
  secondaryCta?: CtaBlock;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type StatSection = {
  _type: 'statSection';
  heading?: string;
  stats?: Array<{
    number?: number;
    suffix?: string;
    label?: string;
    _type: 'statItem';
    _key: string;
  }>;
};

export type QuoteSection = {
  _type: 'quoteSection';
  quote?: string;
  attribution?: string;
  detail?: string;
  anchor?: Slug;
};

export type GallerySection = {
  _type: 'gallerySection';
  heading?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
    _key: string;
  }>;
  columns?: 2 | 3 | 4;
  anchor?: Slug;
};

export type ImageTextSection = {
  _type: 'imageTextSection';
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  imageSide?: 'left' | 'right';
  eyebrow?: string;
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: CtaBlock;
  detail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  anchor?: Slug;
};

export type RichTextSection = {
  _type: 'richTextSection';
  eyebrow?: string;
  heading?: string;
  scriptAccent?: string;
  headingAccent?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  width?: 'normal' | 'narrow';
  align?: 'left' | 'center';
  anchor?: Slug;
};

export type HeroSection = {
  _type: 'heroSection';
  eyebrow?: string;
  headline?: string;
  headingAccent?: string;
  subhead?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  layout?: 'full' | 'split' | 'window';
  frames?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
    _key: string;
  }>;
  facts?: Array<{
    label?: string;
    value?: string;
    _type: 'heroFact';
    _key: string;
  }>;
  primaryCta?: CtaBlock;
  secondaryCta?: CtaBlock;
  size?: 'tall' | 'short';
};

export type PrivacyPage = {
  _id: string;
  _type: 'privacyPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  lastUpdated?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h2' | 'h3';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      openInNewTab?: boolean;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type JournalEntryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalEntry';
};

export type CtaBlock = {
  _type: 'ctaBlock';
  label?: string;
  linkType?: 'internal' | 'external' | 'email' | 'phone';
  internalLink?: HomePageReference | JournalPageReference | JournalEntryReference | PageReference;
  externalUrl?: string;
  emailAddress?: string;
  phoneNumber?: string;
  openInNewTab?: boolean;
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & SundayTimesSection)
    | ({
        _key: string;
      } & TimelineSection)
    | ({
        _key: string;
      } & StaffGridSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ScriptureBandSection)
    | ({
        _key: string;
      } & HeritageBandSection)
    | ({
        _key: string;
      } & GiveBandSection)
    | ({
        _key: string;
      } & HoursSection)
    | ({
        _key: string;
      } & DocumentListSection)
    | ({
        _key: string;
      } & LinkCardsSection)
    | ({
        _key: string;
      } & MinistrySection)
    | ({
        _key: string;
      } & WatchwordSection)
    | ({
        _key: string;
      } & GoalsSection)
    | ({
        _key: string;
      } & PledgeSection)
    | ({
        _key: string;
      } & LetterSection)
    | ({
        _key: string;
      } & ChurchTracFormSection)
  >;
  addToMainNav?: boolean;
  navGroup?: 'top' | 'services' | 'resources';
  navLabel?: string;
  addToFooter?: boolean;
  archived?: boolean;
  seoPreview?: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  hideFromSearch?: boolean;
  publishAt?: string;
};

export type JournalCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'journalCategory';
};

export type JournalEntry = {
  _id: string;
  _type: 'journalEntry';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: 'image';
  };
  categories?: Array<
    {
      _key: string;
    } & JournalCategoryReference
  >;
  tags?: Array<string>;
  author?: string;
  publishedAt?: string;
  updatedAt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'lead' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<
          | {
              href?: string;
              openInNewTab?: boolean;
              _type: 'link';
              _key: string;
            }
          | {
              vendor?: string;
              url?: string;
              _type: 'sourcedFrom';
              _key: string;
            }
        >;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        size?: 'standard' | 'wide' | 'full';
        _type: 'inlineImage';
        _key: string;
      }
    | {
        quote?: string;
        attribution?: string;
        _type: 'pullQuote';
        _key: string;
      }
    | {
        beforeImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        afterImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        caption?: string;
        _type: 'beforeAfter';
        _key: string;
      }
    | {
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: 'image';
        };
        itemName?: string;
        vendor?: string;
        price?: string;
        url?: string;
        notes?: string;
        _type: 'sourceCard';
        _key: string;
      }
    | {
        label?: string;
        content?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
          }>;
          style?: 'normal';
          listItem?: 'bullet';
          markDefs?: Array<{
            href?: string;
            openInNewTab?: boolean;
            _type: 'link';
            _key: string;
          }>;
          level?: number;
          _type: 'block';
          _key: string;
        }>;
        _type: 'tipCallout';
        _key: string;
      }
    | {
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: 'image';
          _key: string;
        }>;
        layout?: 'grid2' | 'grid3' | 'row';
        caption?: string;
        _type: 'imageGallery';
        _key: string;
      }
    | {
        style?: 'line' | 'ornament' | 'space';
        _type: 'divider';
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: 'videoEmbed';
        _key: string;
      }
  >;
  seoTitle?: string;
  seoDescription?: string;
  relatedPosts?: Array<
    {
      _key: string;
    } & JournalEntryReference
  >;
};

export type JournalPage = {
  _id: string;
  _type: 'journalPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroEyebrow?: string;
  heroHeadline?: string;
  heroSubhead?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  heroScriptAccent?: string;
  stickyCtaLabel?: string;
  finalCtaHeadline?: string;
  finalCtaScriptAccent?: string;
  finalCtaSubhead?: string;
  finalCta?: CtaBlock;
  finalCtaBackgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  additionalSections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & SundayTimesSection)
    | ({
        _key: string;
      } & TimelineSection)
    | ({
        _key: string;
      } & StaffGridSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ScriptureBandSection)
    | ({
        _key: string;
      } & HeritageBandSection)
    | ({
        _key: string;
      } & GiveBandSection)
    | ({
        _key: string;
      } & HoursSection)
    | ({
        _key: string;
      } & DocumentListSection)
    | ({
        _key: string;
      } & LinkCardsSection)
    | ({
        _key: string;
      } & MinistrySection)
    | ({
        _key: string;
      } & WatchwordSection)
    | ({
        _key: string;
      } & GoalsSection)
    | ({
        _key: string;
      } & PledgeSection)
    | ({
        _key: string;
      } & LetterSection)
    | ({
        _key: string;
      } & ChurchTracFormSection)
  >;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & RichTextSection)
    | ({
        _key: string;
      } & ImageTextSection)
    | ({
        _key: string;
      } & GallerySection)
    | ({
        _key: string;
      } & QuoteSection)
    | ({
        _key: string;
      } & StatSection)
    | ({
        _key: string;
      } & CtaBandSection)
    | ({
        _key: string;
      } & VideoSection)
    | ({
        _key: string;
      } & SpacerSection)
    | ({
        _key: string;
      } & LogoStripSection)
    | ({
        _key: string;
      } & EmbedSection)
    | ({
        _key: string;
      } & SundayTimesSection)
    | ({
        _key: string;
      } & TimelineSection)
    | ({
        _key: string;
      } & StaffGridSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ScriptureBandSection)
    | ({
        _key: string;
      } & HeritageBandSection)
    | ({
        _key: string;
      } & GiveBandSection)
    | ({
        _key: string;
      } & HoursSection)
    | ({
        _key: string;
      } & DocumentListSection)
    | ({
        _key: string;
      } & LinkCardsSection)
    | ({
        _key: string;
      } & MinistrySection)
    | ({
        _key: string;
      } & WatchwordSection)
    | ({
        _key: string;
      } & GoalsSection)
    | ({
        _key: string;
      } & PledgeSection)
    | ({
        _key: string;
      } & LetterSection)
    | ({
        _key: string;
      } & ChurchTracFormSection)
    | ({
        _key: string;
      } & TeamSection)
    | ({
        _key: string;
      } & DynamicListSection)
  >;
  seoTitle?: string;
  seoDescription?: string;
  seoImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type MediaTag = {
  _id: string;
  _type: 'media.tag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | TimelineRowImage
  | SanityFileAssetReference
  | ListedDocumentFile
  | LinkCardImage
  | Photo
  | Redirect
  | SectionPreset
  | StaffMember
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | JournalCategory
  | Announcement
  | StudioNotes
  | StudioGuide
  | NotFoundPage
  | BusinessInfo
  | SiteSettings
  | HomePageReference
  | JournalPageReference
  | PrivacyPageReference
  | PageReference
  | NavLink
  | DynamicListSection
  | TeamSection
  | ChurchTracFormReference
  | ChurchTracFormSection
  | ChurchTracForm
  | LetterSection
  | PledgeSection
  | GoalsSection
  | WatchwordSection
  | MinistryReference
  | MinistrySection
  | StaffMemberReference
  | Ministry
  | LinkCardsSection
  | DocumentListSection
  | HoursSection
  | GiveBandSection
  | HeritageBandSection
  | ScriptureBandSection
  | FaqSection
  | StaffGridSection
  | TimelineSection
  | SundayTimesSection
  | EmbedSection
  | LogoStripSection
  | SpacerSection
  | VideoSection
  | CtaBandSection
  | StatSection
  | QuoteSection
  | GallerySection
  | ImageTextSection
  | RichTextSection
  | HeroSection
  | PrivacyPage
  | JournalEntryReference
  | CtaBlock
  | Page
  | JournalCategoryReference
  | JournalEntry
  | JournalPage
  | HomePage
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
