// scripts/lib/approval-note.mjs
//
// Pure rendering for docs/superpowers/notes/2026-09-19-copy-for-church-approval.md.
// Extracted out of scripts/seed-pages.mjs so it can be unit-tested without
// touching disk, Sanity, or the CLI's --only filtering, and so the CHROME
// SECTIONS below have exactly one definition.
//
// THE BUG THIS FILE FIXES (2026-09-24): seed-pages.mjs's approval-note writer
// only ever knew about page modules (scripts/pages/*.mjs) and the constant
// FACTS_TO_CONFIRM. "Site footer (every page)" and "Header and mobile menu
// (every page)" carry copy that belongs to NO page module (the footer credit,
// the "Watch live" / "Live now" labels: UI strings, not a page's pageBuilder),
// so nobody generated them. They were typed straight into the committed note
// by hand across three commits, and the note is regenerated from scratch on
// EVERY run (dry or wet, --only or full, per the "ONE APPROVAL NOTE"
// guarantee in seed-pages.mjs's header) — so the next run of ANYTHING wiped
// them silently. It was never actually about --only: a bare `node
// scripts/seed-pages.mjs` with no flags reproduces the same 17-line loss.
//
// THE FIX. CHROME_SECTIONS below is a code constant, the same move already
// used for FACTS_TO_CONFIRM: copy that has no Sanity document behind it lives
// here, in the generator, instead of surviving only as hand-typed prose in a
// generated file. It costs nothing to keep current (no network, no Sanity
// project needed) and it is now impossible for a run to "forget" it, because
// renderApprovalNote() always emits it, independent of which page modules the
// caller passed in. That is also why this file takes `mods` as a plain array
// rather than reading scripts/pages/ itself: seed-pages.mjs already computes
// `all` (every non-hidden page module, regardless of --only) once, and this
// function trusts that input rather than re-deriving it, so there is exactly
// one place that decides "all page modules" and one place that decides
// "chrome copy", and neither can partially update without the other noticing
// in a test.
export const CHROME_SECTIONS = [
  {
    heading: 'Site footer (every page)',
    newCopy: [
      'An American Baptist congregation in downtown Muncie since 1859. (the footer\'s bottom line, under Praise & Proclaim; built from "We Are American Baptists" on Beliefs, and "Founded in 1859" and "downtown Muncie" on History)',
      '"Designed by Nixon Creative Studio" (the base rail\'s credit, always shown; Site settings\' footer credit overrides it). Approved by Nathan 2026-09-24.',
    ],
    // No `edits` key at all: the footer section has never carried an "Edits
    // to the church's own text" heading (there is no church text in it to
    // edit), and that is a real difference from a page module, whose edits
    // section prints even when empty (a "(none: ...)" fallback line). Adding
    // one here would be a cosmetic change to a note this file must reproduce
    // byte-for-byte, not a fix.
  },
  {
    heading: 'Header and mobile menu (every page)',
    newCopy: [
      '"Watch live", and "Live now" during the Sunday service (the link to the live stream beside Give). UI labels, approved by Nathan 2026-09-24.',
    ],
    edits: ["(none: the goals' names and small lines are Who We Are's own)"],
  },
];

/** `manifest[key].alt`, following `.same` chains, matching seed-pages.mjs's altFor. */
function altFor(manifest, key) {
  const entry = manifest?.[key];
  if (!entry) return '(not in scripts/data/page-images.json)';
  if (entry.alt) return entry.alt;
  if (entry.same) return altFor(manifest, entry.same);
  return '(no alt text)';
}

/**
 * Render the full approval-note markdown from a list of page modules (already
 * filtered to "every non-hidden module", independent of any --only the CLI
 * was given) and the page-images manifest. Pure: no fs, no Sanity, no
 * randomness, so the same inputs always produce the same string.
 * @param {Array<{slug:string,newCopy?:string[],edits?:string[],confirm?:string[],photoConsent?:string[]}>} mods
 * @param {Record<string, {alt?:string, same?:string}>} manifest
 * @param {string[]} factsToConfirm
 */
export function renderApprovalNote(mods, manifest, factsToConfirm) {
  const lines = [];
  lines.push('# Copy for the church to approve');
  lines.push('');
  lines.push(
    'Sentences on the new site that did not exist on the Wix site, for the church to approve or replace. Everything else is the church’s own text, edited only by cutting. Generated by scripts/seed-pages.mjs; do not edit by hand.',
  );
  lines.push('');

  for (const mod of mods) {
    lines.push(`## /${mod.slug}`);
    lines.push('');
    lines.push('### New sentences');
    lines.push('');
    const newCopy = mod.newCopy ?? [];
    if (newCopy.length === 0)
      lines.push('- (none: every sentence on this page is the church’s own)');
    else for (const s of newCopy) lines.push(`- ${s}`);
    lines.push('');
    lines.push('### Edits to the church’s own text');
    lines.push('');
    const edits = mod.edits ?? [];
    if (edits.length === 0) lines.push('- (none: their text is cut, never reworded)');
    else for (const e of edits) lines.push(`- ${e}`);
    lines.push('');
    const confirm = mod.confirm ?? [];
    if (confirm.length > 0) {
      lines.push('### Facts to confirm from this page');
      lines.push('');
      for (const c of confirm) lines.push(`- ${c}`);
      lines.push('');
    }
    lines.push('### Photos of children');
    lines.push('');
    const photos = mod.photoConsent ?? [];
    if (photos.length === 0) lines.push('- (none)');
    else for (const k of photos) lines.push(`- ${k}: ${altFor(manifest, k)}`);
    lines.push('');
  }

  // Chrome copy: always emitted, regardless of which page modules `mods`
  // carries, because none of it is a page module's to lose.
  for (const section of CHROME_SECTIONS) {
    lines.push(`## ${section.heading}`);
    lines.push('');
    lines.push('### New sentences');
    lines.push('');
    for (const s of section.newCopy ?? []) lines.push(`- ${s}`);
    lines.push('');
    if (section.edits) {
      lines.push('### Edits to the church’s own text');
      lines.push('');
      for (const e of section.edits) lines.push(`- ${e}`);
      lines.push('');
    }
  }

  lines.push('## Facts the church must confirm');
  lines.push('');
  factsToConfirm.forEach((fact, i) => lines.push(`${i + 1}. ${fact}`));
  lines.push('');

  return lines.join('\n');
}
